//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
//using System.ComponentModel.DataAnnotations.Schema;
using System.Data;

namespace CZOA.DB
{
    using System;
    using System.Collections.Generic;
    //[Table("T_ATTA", Schema = Config.DbSchema)]
    public partial class T_ATTA
    {
        public decimal ENTITY_ID { get; set; }
        [Key]
        public decimal ATTA_ID { get; set; }
        public decimal ATTA_RECORD_ID { get; set; }
        public string ATTA_FILE_NAME { get; set; }
        public decimal ATTA_FILE_TYPE_TI { get; set; }
        public decimal ATTA_IDX { get; set; }
        //[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public Nullable<System.DateTime> TS { get; set; }
        //[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public Nullable<decimal> RS { get; set; }
    }
}
