//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
//using System.ComponentModel.DataAnnotations.Schema;

namespace CZOA.DB
{
    using System;
    using System.Collections.Generic;
    //[Table("T_ATTA_RECORD", Schema = Config.DbSchema)]
    public partial class T_ATTA_RECORD
    {
        public decimal ENTITY_ID { get; set; }
        public decimal ATTA_ID { get; set; }
        [Key]
        public decimal ATTA_RECORD_ID { get; set; }
        public string ATTA_URI { get; set; }
        public decimal RECORD_ACTION_TI { get; set; }
        public decimal DEPT_ID { get; set; }
        public decimal ROLE_ID { get; set; }
        public decimal USER_ID { get; set; }
        //[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public Nullable<System.DateTime> TS { get; set; }
        //[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public Nullable<decimal> RS { get; set; }
    }
}
