//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
//using System.ComponentModel.DataAnnotations.Schema;

namespace CZOA.DB
{
    using System;
    using System.Collections.Generic;
    //[Table("T_COMMENT", Schema = Config.DbSchema)]
    public partial class T_COMMENT
    {
        [Key]
        public decimal COMMENT_ID { get; set; }
        public decimal WORK_ID { get; set; }
        public decimal NODE_ID { get; set; }
        public decimal COMMENT_TYPE_TI { get; set; }
        public decimal COMMENT_ON { get; set; }
        public string COMMENT_CONTENT { get; set; }
        public decimal COMMENT_SCORE { get; set; }
        public System.DateTime COMMENT_TIME { get; set; }
        //[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public Nullable<System.DateTime> TS { get; set; }
        //[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public Nullable<decimal> RS { get; set; }
    }
}