//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
//using System.ComponentModel.DataAnnotations.Schema;

namespace CZOA.DB
{
    using System;
    using System.Collections.Generic;
    //[Table("T_ENTITY_ITEM", Schema = Config.DbSchema)]
    public partial class T_ENTITY_ITEM
    {
        public decimal NODE_ID { get; set; }
        public decimal ENTITY_ID { get; set; }
        public Nullable<decimal> MODEL_ITEM_ID { get; set; }
        [Key]
        public decimal ENTITY_ITEM_ID { get; set; }
        public Nullable<decimal> SUPER_ENTITY_ITEM_ID { get; set; }
        public string ITEM_NAME { get; set; }
        public decimal DEPT_ID { get; set; }
        //public decimal ROLE_ID { get; set; }
        public decimal USER_ID { get; set; }
        public decimal ITEM_VALUE_TYPE_TI { get; set; }
        //public string ITEM_VALUE_NUMBER { get; set; }
        //public string ITEM_VALUE_STRING { get; set; }
        //public Nullable<System.DateTime> ITEM_VALUE_TIME { get; set; }
        public string ITEM_VALUE { get; set; }
        public byte[] ITEM_VALUE_BINARY { get; set; }
        public Nullable<decimal> CREATE_SEQ { get; set; }
        public decimal ACTIVE_TI { get; set; }
        //[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public Nullable<System.DateTime> TS { get; set; }
        //[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public Nullable<decimal> RS { get; set; }
    }
}
