//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
//using System.ComponentModel.DataAnnotations.Schema;

namespace CZOA.DB
{
	using System;
	using System.Collections.Generic;
	//[Table("T_FLOW", Schema = Config.DbSchema)]
	public partial class T_FLOW
	{
		[Key]
		public decimal FLOW_ID { get; set; }
		public string FLOW_NAME { get; set; }
		public decimal FLOW_CATEGORY_TI { get; set; }
		//public string FLOW_CATEGORY_TI_NAME { get; set; }

		public decimal FLOW_IDX { get; set; }
		public byte[] FLOW_MAP { get; set; }
		public decimal OUTER_ORG_FLOW { get; set; }
		public decimal ENABLED { get; set; }
        public decimal? ORG_ID { get; set; }
        public decimal? WORK_CATEGORY_TI { get; set; }
		//[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
		public Nullable<System.DateTime> TS { get; set; }
		//[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
		public Nullable<decimal> RS { get; set; }
	}
}
