//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
//using System.ComponentModel.DataAnnotations.Schema;

namespace CZOA.DB
{
    using System;
    using System.Collections.Generic;
    //[Table("T_FORM", Schema = Config.DbSchema)]
    public partial class T_FORM
    {
        //public Nullable<decimal> MODEL_ID { get; set; }
        [Key]
        public decimal FORM_ID { get; set; }
        public string FORM_NAME { get; set; }
        public decimal FORM_TYPE_TI { get; set; }
        public string FORM_URI { get; set; }
        public string FORM_ASSEMBLY_CLASS { get; set; }
        public decimal FORM_IDX { get; set; }
        public byte[] FORM_BODY { get; set; }
        public decimal? ORG_ID { get; set; }
        //[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public Nullable<System.DateTime> TS { get; set; }
        //[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public Nullable<decimal> RS { get; set; }
    }
}
