//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
//using System.ComponentModel.DataAnnotations.Schema;

namespace CZOA.DB
{
    using System;
    using System.Collections.Generic;
    //[Table("T_MODEL", Schema = Config.DbSchema)]
    public partial class T_MODEL
    {
        [Key]
        public decimal MODEL_ID { get; set; }
        public Nullable<decimal> FORM_ID { get; set; }
        public string MODEL_NAME { get; set; }
        public decimal RANGE_RANK_TI { get; set; }
        public decimal MODEL_TYPE_TI { get; set; }
        public decimal MODEL_LEVEL_TI { get; set; }
        public Nullable<decimal> COPY_MODEL_FROM { get; set; }
        public decimal IS_CONTROL_ITEMS { get; set; }
        public decimal MODEL_IDX { get; set; }
        public decimal? ORG_ID { get; set; }
        //[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public Nullable<System.DateTime> TS { get; set; }
        //[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public Nullable<decimal> RS { get; set; }
    }
}
