//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
//using System.ComponentModel.DataAnnotations.Schema;

namespace CZOA.DB
{
    using System;
    using System.Collections.Generic;
    //[Table("T_NODE", Schema = Config.DbSchema)]
    
    public partial class T_NODE
    {
        public decimal WORK_ID { get; set; }
        public decimal LINE_ID { get; set; }
        public decimal STAGE_ID { get; set; }
        public Nullable<decimal> PREV_NODE_ID { get; set; }
        [Key]
        public decimal NODE_ID { get; set; }
        public decimal STEP_ID { get; set; }
        public string NODE_STEP_NAME { get; set; }
        public decimal WAITING_BRANCH { get; set; }
        public decimal LINE_HEADER { get; set; }
        public decimal LINE_ENDING { get; set; }
        public decimal ARRIVE_ACTION { get; set; }
        public decimal DO_STATUS { get; set; }
        public decimal STATUS { get; set; }
        public Nullable<System.DateTime> WAITDO_TIME { get; set; }
        public Nullable<System.DateTime> DOING_TIME { get; set; }
        public Nullable<System.DateTime> DONE_TIME { get; set; }
        //[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public Nullable<System.DateTime> TS { get; set; }
        //[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public Nullable<decimal> RS { get; set; }
    }
}
