//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
//using System.ComponentModel.DataAnnotations.Schema;

namespace CZOA.DB
{
    using System;
    using System.Collections.Generic;
    //[Table("T_ORG", Schema = Config.DbSchema)]
    public partial class T_ORG
    {
        [Key]
        public decimal ORG_ID { get; set; }
        public Nullable<decimal> SUPER_ORG_ID { get; set; }
        public string ORG_NAME { get; set; }
        public string ORG_CODE { get; set; }
        public decimal ORG_TYPE_TI { get; set; }
        public decimal? INCOMING_DEPT { get; set; }
        public decimal? INCOMING_ROLE { get; set; }
        public decimal ORG_IDX { get; set; }
        //[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public Nullable<System.DateTime> TS { get; set; }
        //[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public Nullable<decimal> RS { get; set; }
    }
}
