//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
//using System.ComponentModel.DataAnnotations.Schema;

namespace CZOA.DB
{
    using System;
    using System.Collections.Generic;
    //[Table("T_STEP", Schema = Config.DbSchema)]
    public partial class T_STEP
    {
        public decimal FLOW_ID { get; set; }
        [Key]
        public decimal STEP_ID { get; set; }
        public string STEP_NAME { get; set; }
        public decimal STEP_NO { get; set; }
        public decimal ENTER_IN_STEP { get; set; }
        public decimal ADD_FORM_STEP { get; set; }
        public decimal SELF_BEGIN_FLOW_STEP { get; set; }
        public decimal NEXT_BEGIN_FLOW_STEP { get; set; }
        public decimal BEGIN_ASSIST_BRANCH_STEP { get; set; }
        public decimal BEGIN_PARALLEL_BRANCH_STEP { get; set; }
        public decimal BRANCH_LINE_HEADER_STEP { get; set; }
        public decimal PARALLEL_MERGE_STEP { get; set; }
        public decimal MANUAL_ENDING_STEP { get; set; }
        public decimal AUTO_ENDING_STEP { get; set; }
        //public decimal OUTER_ORG_STEP { get; set; }
        public Nullable<System.DateTime> DONE_DATE { get; set; }
        public decimal? DONE_DAYS { get; set; }
        public decimal COMMENT_TYPE_TI { get; set; }
        public decimal IS_ASSIGN_USER { get; set; }
        public string STEP_GUID { get; set; }
        //[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public Nullable<System.DateTime> TS { get; set; }
        //[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public Nullable<decimal> RS { get; set; }
    }
}
