//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
//using System.ComponentModel.DataAnnotations.Schema;

namespace CZOA.DB
{
    using System;
    using System.Collections.Generic;
    //[Table("T_WORK", Schema = Config.DbSchema)]
    public partial class T_WORK
    {
        [Key]
        public decimal WORK_ID { get; set; }
        public decimal ORG_ID { get; set; }
        public string WORK_NAME { get; set; }
        public decimal WORK_TYPE_TI { get; set; }
        public Nullable<decimal> WORK_NO { get; set; }
        public decimal WORK_LEVEL_TI { get; set; }
        public decimal WORK_DO_STATUS_TI { get; set; }
        public Nullable<System.DateTime> START_TIME {get;set;}
        public Nullable<System.DateTime> FINISH_TIME { get; set; }
        public decimal WORK_SOURCE_TI { get; set; }
        public decimal HOST_DEPT { get; set; }
        public decimal WORK_CATEGORY_TI { get; set; }
        public Nullable<decimal> SUPERVISION_TYPE_TI { get; set; }
        public Nullable<System.DateTime> SUPERVISION_START_TIME { get; set; }
        public Nullable<System.DateTime> SUPERVISION_FINISH_TIME { get; set; }
        //[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public Nullable<System.DateTime> TS { get; set; }
        //[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public Nullable<decimal> RS { get; set; }
    }
}
